name:                taggable
version:             0.1.0.0
github:              "SlimTim10/taggable"
license:             MIT
author:              "SlimTim10"
maintainer:          "slimtim10@gmail.com"
copyright:           "SlimTim10"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            none

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SlimTim10/taggable#readme>

dependencies:
- base >= 4.7 && < 5
- sqlite-simple >= 0.4.18.0 && < 0.5
- direct-sqlite >= 2.3.13 && < 2.4
- raw-strings-qq >= 1.1 && < 1.2
- directory >= 1.3.6.1 && < 1.4
- transformers >= 0.5.6.2 && < 0.6
- optparse-applicative >= 0.15.0.0 && < 0.16

library:
  source-dirs: src

executables:
  taggable-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taggable

tests:
  taggable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taggable
    - hspec

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - DeriveAnyClass
  - DuplicateRecordFields
  - NamedFieldPuns
  - ParallelListComp

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
